### ISSUE TITLE
upgrade to OF 0.10.1 ?

### ISSUE THREAD

**Issue by antimodular** [charlesveasey/ofxBezierSurface#2]
just moved your addon over to OF 0.10.1 but get a bunch off xml.addChild, xml.setTo etc. compile errors.
i was wondering if you had an updated version already kicking around?
i will see if i can fix it on my end too.

thank you for a great addon.

**Comment by charlesveasey** [comment]
I haven't updated to OF 0.1. Let me know if you do.

**Comment by charlesveasey** [comment]
Thanks for the update. It's been merged.
